name: Cloud Run Blue-Green Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      action:
        description: '执行动作 (deploy, promote, abort)'
        required: true
        default: 'deploy'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          # 获取这个值：projects/项目编号/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          workload_identity_provider: 'projects/project-95db9422-29d0-4c5e-b9f/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions-deployer@project-95db9422-29d0-4c5e-b9f.iam.gserviceaccount.com'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Execute Blue-Green Action'
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh ${{ github.event.inputs.action || 'deploy' }}